-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 20:09:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `ID` VARCHAR(30) NOT NULL,
  `full name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pantheon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pantheon` (
  `position` INT NOT NULL,
  PRIMARY KEY (`position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `full name` VARCHAR(30) NOT NULL,
  `age` INT UNSIGNED NULL,
  `ID` VARCHAR(30) NOT NULL,
  `Player_ID` VARCHAR(30) NOT NULL,
  `Pantheon_position` INT NULL,
  `Point` FLOAT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Director_Player1_idx` (`Player_ID` ASC) VISIBLE,
  INDEX `fk_Director_Pantheon1_idx` (`Pantheon_position` ASC) VISIBLE,
  CONSTRAINT `fk_Director_Player1`
    FOREIGN KEY (`Player_ID`)
    REFERENCES `mydb`.`Player` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_Pantheon1`
    FOREIGN KEY (`Pantheon_position`)
    REFERENCES `mydb`.`Pantheon` (`position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenario` (
  `ID` VARCHAR(30) NOT NULL,
  `Director_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Scenario_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Scenario_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `year` INT UNSIGNED NULL,
  `company` VARCHAR(30) NULL,
  `duration` INT UNSIGNED NULL,
  `title` VARCHAR(30) NULL,
  `ID` VARCHAR(30) NOT NULL,
  `Director_ID` VARCHAR(30) NOT NULL,
  `type_name` VARCHAR(30) NOT NULL,
  `Scenario_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Movie_Director1_idx` (`Director_ID` ASC) VISIBLE,
  INDEX `fk_Movie_type1_idx` (`type_name` ASC) VISIBLE,
  INDEX `fk_Movie_Scenario1_idx` (`Scenario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_type1`
    FOREIGN KEY (`type_name`)
    REFERENCES `mydb`.`Type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Scenario1`
    FOREIGN KEY (`Scenario_ID`)
    REFERENCES `mydb`.`Scenario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sponsor` (
  `Full name` VARCHAR(30) NULL,
  `ID` VARCHAR(30) NOT NULL,
  `Money` DOUBLE UNSIGNED NULL,
  `Movie_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Sponsor_Movie1_idx` (`Movie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sponsor_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor` (
  `Full name` VARCHAR(100) NULL,
  `ID` VARCHAR(30) NOT NULL,
  `Photo` VARCHAR(30) NULL,
  `date of birth` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_is_from_the_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_is_from_the_Country` (
  `Director_ID` VARCHAR(30) NOT NULL,
  `Country_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Director_ID`, `Country_name`),
  INDEX `fk_Director_has_Country_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Country_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_is_from_the_Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_is_from_the_Country` (
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Country_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Actor_ID`, `Country_name`),
  INDEX `fk_Actor_has_Country_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Country_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Countries` (
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie` (
  `Movie_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Movie_ID`),
  CONSTRAINT `fk_International Movie_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scenery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scenery` (
  `ID` VARCHAR(30) NOT NULL,
  `title` VARCHAR(30) NULL,
  `description` VARCHAR(30) NULL,
  `International Movie_Movie_ID` VARCHAR(30) NOT NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`, `Countries_name`),
  INDEX `fk_Scenery_International Movie1_idx` (`International Movie_Movie_ID` ASC) VISIBLE,
  INDEX `fk_Scenery_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Scenery_International Movie1`
    FOREIGN KEY (`International Movie_Movie_ID`)
    REFERENCES `mydb`.`International Movie` (`Movie_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scenery_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `Name` VARCHAR(30) NOT NULL,
  `TK` VARCHAR(30) NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Name`, `Countries_name`),
  INDEX `fk_Cities_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_as_a_Sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_as_a_Sponsor` (
  `Movie_title` VARCHAR(30) NOT NULL,
  `Movie_company` VARCHAR(30) NOT NULL,
  `Movie_year` INT UNSIGNED NOT NULL,
  `Sponsor_Full name` INT NOT NULL,
  `Money` VARCHAR(45) NULL,
  PRIMARY KEY (`Movie_title`, `Movie_company`, `Movie_year`, `Sponsor_Full name`),
  INDEX `fk_Movie_has_Sponsor_Sponsor1_idx` (`Sponsor_Full name` ASC) VISIBLE,
  INDEX `fk_Movie_has_Sponsor_Movie1_idx` (`Movie_title` ASC, `Movie_company` ASC, `Movie_year` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Sponsor_Movie1`
    FOREIGN KEY (`Movie_title` , `Movie_company` , `Movie_year`)
    REFERENCES `mydb`.`Movie` (`title` , `company` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Sponsor_Sponsor1`
    FOREIGN KEY (`Sponsor_Full name`)
    REFERENCES `mydb`.`Sponsor` (`Full name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `ID` VARCHAR(30) NOT NULL,
  `full name` VARCHAR(30) NULL,
  `description` VARCHAR(30) NULL,
  `Actor_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Roles_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contracts` (
  `code` VARCHAR(30) NOT NULL,
  `date of start` DATE NOT NULL,
  `date of end` DATE NOT NULL,
  `salary of one year` DOUBLE UNSIGNED NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_has_Director_as_an_idol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_has_Director_as_an_idol` (
  `Director_ID` VARCHAR(30) NOT NULL,
  `Director_ID1` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Director_ID`, `Director_ID1`),
  INDEX `fk_Director_has_Director_Director4_idx` (`Director_ID1` ASC) VISIBLE,
  INDEX `fk_Director_has_Director_Director3_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Director_Director3`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Director_Director4`
    FOREIGN KEY (`Director_ID1`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_Actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_Actor` (
  `Movie_ID` VARCHAR(30) NOT NULL,
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Contracts_code` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Movie_ID`, `Actor_ID`),
  INDEX `fk_Movie_has_Actor_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  INDEX `fk_Movie_has_Actor_Movie1_idx` (`Movie_ID` ASC) VISIBLE,
  INDEX `fk_Movie_has_Actor_Contracts1_idx` (`Contracts_code` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Actor_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Actor_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Actor_Contracts1`
    FOREIGN KEY (`Contracts_code`)
    REFERENCES `mydb`.`Contracts` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domestical Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domestical Movie` (
  `Movie_ID` VARCHAR(30) NOT NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Movie_ID`, `Countries_name`),
  INDEX `fk_Domestical Movie_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Domesticall Movie_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domestical Movie_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AI` (
  `name` VARCHAR(30) NOT NULL,
  `type_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_AI_type1_idx` (`type_name` ASC) VISIBLE,
  CONSTRAINT `fk_AI_type1`
    FOREIGN KEY (`type_name`)
    REFERENCES `mydb`.`Type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scripture text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scripture text` (
  `Code` VARCHAR(30) NOT NULL,
  `Scripture text_Code` VARCHAR(30) NULL,
  `Time` INT UNSIGNED NULL,
  `AI_name` VARCHAR(30) NOT NULL,
  `Scenario_ID` VARCHAR(30) NOT NULL,
  INDEX `fk_Scripture text_Scripture text1_idx` (`Scripture text_Code` ASC) VISIBLE,
  PRIMARY KEY (`Code`),
  INDEX `fk_Scripture text_AI1_idx` (`AI_name` ASC) VISIBLE,
  INDEX `fk_Scripture text_Scenario1_idx` (`Scenario_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Scripture text_Scripture text1`
    FOREIGN KEY (`Scripture text_Code`)
    REFERENCES `mydb`.`Scripture text` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scripture text_AI1`
    FOREIGN KEY (`AI_name`)
    REFERENCES `mydb`.`AI` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Scripture text_Scenario1`
    FOREIGN KEY (`Scenario_ID`)
    REFERENCES `mydb`.`Scenario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Natural characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Natural characteristics` (
  `Type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Spiritual Characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Spiritual Characteristics` (
  `Code` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Educational Programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Educational Programme` (
  `Name` VARCHAR(30) NOT NULL,
  `ID` VARCHAR(30) NOT NULL,
  `Actor_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Educational Programme_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Educational Programme_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technical Characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technical Characteristics` (
  `ID` VARCHAR(30) NOT NULL,
  `Technical Quality` INT NOT NULL,
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Educational Programme_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`, `Technical Quality`, `Actor_ID`),
  INDEX `fk_Technical Characteristics_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  INDEX `fk_Technical Characteristics_Educational Programme1_idx` (`Educational Programme_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Technical Characteristics_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technical Characteristics_Educational Programme1`
    FOREIGN KEY (`Educational Programme_ID`)
    REFERENCES `mydb`.`Educational Programme` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Competition` (
  `name` VARCHAR(30) NOT NULL,
  `date` DATE NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`, `Countries_name`),
  INDEX `fk_Competition_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Competition_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Awards` (
  `ID` VARCHAR(30) NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  `Competition_name` VARCHAR(30) NOT NULL,
  `Movie_ID` VARCHAR(30) NOT NULL,
  `Director_ID` VARCHAR(30) NOT NULL,
  `Points for the winner` INT UNSIGNED NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Awards_Competition1_idx` (`Competition_name` ASC) VISIBLE,
  INDEX `fk_Awards_Movie1_idx` (`Movie_ID` ASC) VISIBLE,
  INDEX `fk_Awards_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Awards_Competition1`
    FOREIGN KEY (`Competition_name`)
    REFERENCES `mydb`.`Competition` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Awards_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Awards_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_has_Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_has_Countries` (
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Actor_ID`, `Countries_name`),
  INDEX `fk_Actor_has_Countries_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  INDEX `fk_Actor_has_Countries_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Countries_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Countries_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_is_from_the_Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_is_from_the_Countries` (
  `Director_ID` VARCHAR(30) NOT NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Director_ID`, `Countries_name`),
  INDEX `fk_Director_has_Countries_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  INDEX `fk_Director_has_Countries_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Countries_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Countries_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_has_Spiritual Characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_has_Spiritual Characteristics` (
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Spiritual Characteristics_Code` VARCHAR(30) NOT NULL,
  `Quality` INT UNSIGNED NULL,
  PRIMARY KEY (`Actor_ID`, `Spiritual Characteristics_Code`),
  INDEX `fk_Actor_has_Spiritual Characteristics_Spiritual Characteri_idx` (`Spiritual Characteristics_Code` ASC) VISIBLE,
  INDEX `fk_Actor_has_Spiritual Characteristics_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Spiritual Characteristics_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Spiritual Characteristics_Spiritual Characterist1`
    FOREIGN KEY (`Spiritual Characteristics_Code`)
    REFERENCES `mydb`.`Spiritual Characteristics` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actor_has_Natural characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actor_has_Natural characteristics` (
  `Actor_ID` VARCHAR(30) NOT NULL,
  `Natural characteristics_Type` VARCHAR(30) NOT NULL,
  `Quality` INT UNSIGNED NULL,
  PRIMARY KEY (`Actor_ID`, `Natural characteristics_Type`),
  INDEX `fk_Actor_has_Natural characteristics_Natural characteristic_idx` (`Natural characteristics_Type` ASC) VISIBLE,
  INDEX `fk_Actor_has_Natural characteristics_Actor1_idx` (`Actor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Actor_has_Natural characteristics_Actor1`
    FOREIGN KEY (`Actor_ID`)
    REFERENCES `mydb`.`Actor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actor_has_Natural characteristics_Natural characteristics1`
    FOREIGN KEY (`Natural characteristics_Type`)
    REFERENCES `mydb`.`Natural characteristics` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`International Movie_has_Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Movie_has_Countries` (
  `International Movie_Movie_ID` VARCHAR(30) NOT NULL,
  `Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`International Movie_Movie_ID`, `Countries_name`),
  INDEX `fk_International Movie_has_Countries_Countries1_idx` (`Countries_name` ASC) VISIBLE,
  INDEX `fk_International Movie_has_Countries_International Movie1_idx` (`International Movie_Movie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_International Movie_has_Countries_International Movie1`
    FOREIGN KEY (`International Movie_Movie_ID`)
    REFERENCES `mydb`.`International Movie` (`Movie_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_International Movie_has_Countries_Countries1`
    FOREIGN KEY (`Countries_name`)
    REFERENCES `mydb`.`Countries` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_participated_in_the_Competition.`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_participated_in_the_Competition.` (
  `Movie_ID` VARCHAR(30) NOT NULL,
  `Competition_name` VARCHAR(30) NOT NULL,
  `Competition_Countries_name` VARCHAR(30) NOT NULL,
  `statistic` FLOAT NOT NULL,
  PRIMARY KEY (`Movie_ID`, `Competition_name`, `Competition_Countries_name`),
  INDEX `fk_Movie_has_Competition_Competition1_idx` (`Competition_name` ASC, `Competition_Countries_name` ASC) VISIBLE,
  INDEX `fk_Movie_has_Competition_Movie1_idx` (`Movie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Competition_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Competition_Competition1`
    FOREIGN KEY (`Competition_name` , `Competition_Countries_name`)
    REFERENCES `mydb`.`Competition` (`name` , `Countries_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Social media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Social media` (
  `address` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `Competition_name` VARCHAR(30) NOT NULL,
  `Competition_Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`address`),
  INDEX `fk_Social media_Competition1_idx` (`Competition_name` ASC, `Competition_Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Social media_Competition1`
    FOREIGN KEY (`Competition_name` , `Competition_Countries_name`)
    REFERENCES `mydb`.`Competition` (`name` , `Countries_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profile` (
  `address` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `Social media_name` VARCHAR(30) NOT NULL,
  `Director_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`address`),
  INDEX `fk_Profile_Social media1_idx` (`Social media_name` ASC) VISIBLE,
  INDEX `fk_Profile_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_Social media1`
    FOREIGN KEY (`Social media_name`)
    REFERENCES `mydb`.`Social media` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Posts` (
  `address` INT NOT NULL,
  `Likes` INT UNSIGNED NULL,
  `Profile_address` VARCHAR(30) NOT NULL,
  `Director_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`address`),
  INDEX `fk_Posts_Profile1_idx` (`Profile_address` ASC) VISIBLE,
  INDEX `fk_Posts_Director1_idx` (`Director_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Posts_Profile1`
    FOREIGN KEY (`Profile_address`)
    REFERENCES `mydb`.`Profile` (`address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director_upload_a_Post_about_the_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director_upload_a_Post_about_the_movie` (
  `Director_ID` VARCHAR(30) NOT NULL,
  `Posts_address` VARCHAR(30) NOT NULL,
  `Movie_ID` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Director_ID`, `Posts_address`),
  INDEX `fk_Director_has_Posts_Posts1_idx` (`Posts_address` ASC) VISIBLE,
  INDEX `fk_Director_has_Posts_Director1_idx` (`Director_ID` ASC) VISIBLE,
  INDEX `fk_Director_has_Posts_Movie1_idx` (`Movie_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Director_has_Posts_Director1`
    FOREIGN KEY (`Director_ID`)
    REFERENCES `mydb`.`Director` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Posts_Posts1`
    FOREIGN KEY (`Posts_address`)
    REFERENCES `mydb`.`Posts` (`address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Director_has_Posts_Movie1`
    FOREIGN KEY (`Movie_ID`)
    REFERENCES `mydb`.`Movie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profile_has_Profile_as_a_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profile_has_Profile_as_a_friend` (
  `Profile_address` VARCHAR(30) NOT NULL,
  `Profile_address1` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Profile_address`, `Profile_address1`),
  INDEX `fk_Profile_has_Profile_Profile2_idx` (`Profile_address1` ASC) VISIBLE,
  INDEX `fk_Profile_has_Profile_Profile1_idx` (`Profile_address` ASC) VISIBLE,
  CONSTRAINT `fk_Profile_has_Profile_Profile1`
    FOREIGN KEY (`Profile_address`)
    REFERENCES `mydb`.`Profile` (`address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profile_has_Profile_Profile2`
    FOREIGN KEY (`Profile_address1`)
    REFERENCES `mydb`.`Profile` (`address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domestical Movie_used_the_Scenery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domestical Movie_used_the_Scenery` (
  `Domestical Movie_Movie_ID` VARCHAR(30) NOT NULL,
  `Domestical Movie_Countries_name` VARCHAR(30) NOT NULL,
  `Scenery_ID` VARCHAR(30) NOT NULL,
  `Scenery_Countries_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Domestical Movie_Movie_ID`, `Domestical Movie_Countries_name`, `Scenery_ID`, `Scenery_Countries_name`),
  INDEX `fk_Domestical Movie_has_Scenery_Scenery1_idx` (`Scenery_ID` ASC, `Scenery_Countries_name` ASC) VISIBLE,
  INDEX `fk_Domestical Movie_has_Scenery_Domestical Movie1_idx` (`Domestical Movie_Movie_ID` ASC, `Domestical Movie_Countries_name` ASC) VISIBLE,
  CONSTRAINT `fk_Domestical Movie_has_Scenery_Domestical Movie1`
    FOREIGN KEY (`Domestical Movie_Movie_ID` , `Domestical Movie_Countries_name`)
    REFERENCES `mydb`.`Domestical Movie` (`Movie_ID` , `Countries_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domestical Movie_has_Scenery_Scenery1`
    FOREIGN KEY (`Scenery_ID` , `Scenery_Countries_name`)
    REFERENCES `mydb`.`Scenery` (`ID` , `Countries_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
